language: go
sudo: required
dist: trusty

go:
  - 1.10.x
  - 1.11.x

os:
  - linux

env:
  global:
  - PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  matrix:
  - TARGET=amd64

matrix:
  fast_finish: true
  include:
    - os: windows
      env: TARGET=amd64
      go: 1.10.x
    - os: windows
      env: TARGET=amd64
      go: 1.11.x

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/containernetworking/cni/cnitool

script:
 - |
   if [ "${TARGET}" == "amd64" ]; then
     GOARCH="${TARGET}" ./test_${TRAVIS_OS_NAME}.sh
   else
     GOARCH="${TARGET}" ./build_linux.sh
   fi

notifications:
  email: false

git:
  depth: 9999999
