language: go
sudo: required
dist: trusty

os:
  linux
  windows

go:
  - 1.10.x
  - 1.11.x

env:
  global:
  - PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  matrix:
  - TARGET=amd64
  - TARGET=arm
  - TARGET=arm64
  - TARGET=ppc64le
  - TARGET=s390x

matrix:
  fast_finish: true
  exclude:
  - os: windows
    env: TARGET!=amd64

install:
  - sudo apt-get install gcc-multilib gcc-mingw-w64 -y
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/containernetworking/cni/cnitool

script:
 - |
   if [ "${TARGET}" == "amd64" ]; then
     GOARCH="${TARGET}" ./test.sh
   else
     GOARCH="${TARGET}" ./build_linux.sh
   fi

notifications:
  email: false

git:
  depth: 9999999
